### ISSUE TITLE
No overload for method 'GetLocalizations' takes 1 arguments

### ISSUE THREAD

**Issue by loshuliveros** [urbanit/OrchardCMS.Localization-Extensions#1]
In Orchard version 1.8.2 there is problem in TaxonomyTermMovedHandler constructor, method GetLocalizations uses only 1 parameter, but interface 'ILocalizationService' defines 2:

IEnumerable<LocalizationPart> GetLocalizations(IContent contentItem, VersionOptions versionOptions);

**Comment by Piedone** [comment]
Thanks, but you see this issue because the module is only compatible with Orchard 1.9: there is another overload for the method so the module works.

If you wish to use the module with 1.8.x then you can back-port it by simply changing that line to supply `null` as the second argument.

**Comment by loshuliveros** [comment]
Hi Piedone,
thanks for info. I used null but i wasn't sure if it is ok.

I tried using Example 2 to create and translate taxonomy, but as default language i used my native sk-SK, other are de-DE, en-GB (en-US was removed).
It seems it works to step 6, i'm able to create translations for taxonomy and for created taxonomy items, but i see only sk-SK term in my sk-SK taxonomy. If i edit this term, i see it's translations, but in translated taxonomies there aren't translated terms.

Maybe i should use Orchard 1.9, but there i couldn't find any working language switcher. In version 1.8.2 i use Datwendo.Localization, which works well there, but it isn't compatible with 1.9 version. Please could you help?

**Comment by Piedone** [comment]
Hmm, without looking much into this I'd first suggest you to please use Orchard 1.9. There were a lot of localization changes and our module builds on them. I don't know about why this particular incompatibility is though.

**Comment by loshuliveros** [comment]
I would like to switch to Orchard 1.9, but do you know some working language switcher? Which one do you use or how do you change language?

**Comment by Piedone** [comment]
Yes, Orchard 1.9 has culture switchers included. There is one called `FrontEndCultureSelector`. Now unfortunately there's no widget for it, you have to display this shape yourself, but it works.

**Comment by loshuliveros** [comment]
Thank you very much, i will try it.

**Comment by loshuliveros** [comment]
Perfect, Example 2 done, works well as is written.
But last paragraph "Localized content items with TaxonomyPickerField step-by-step" doesn't work for me. I created content item and added LocalizationPart. From fields i can choose only Taxonomy Field (there isn't any "TaxonomyPickerField"), but i think you thought this. I configure it for 1. taxonomy/language. Then i added other 2 fields for other 2 taxonomies/languages. When i try create my new content item, yes - there is only Title and language picker, but no Save button. Also other parts aren't visible (Body, Common, Autoroute etc.) but if i understand well, it should be reachable after first saving.
I had use Dev version of Orchard 1.9 because of installation problems with Autofac after building in VS 2015 RC, i found articles where you commented this feed...
I don't know if it is problem of this extension, or new issue should be created somewhere else.

**Comment by Piedone** [comment]
Hmm, I can confirm that this works with the released 1.9 version so I don't know why you see this issue, quite strange. Maybe this is some new incompatibility...

And yes, that should read Taxonomy Field.

**Comment by loshuliveros** [comment]
Hmmm, i was so near to reach my goal...
If i remove this taxonomy field from my content item type and i create new content item, then there are all parts and save button too.

**Comment by loshuliveros** [comment]
OK, now i tested it on VS 2013 and Orchard 1.9 and it works fine, thank you.
I tried to make menu (navigation) from my early created taxonomies and then i would like to create a widget with categories. I know, it's out of scope of this module, but can you explain how can i do it?
1. I added LocalizationPart to Menu content type and i have created new menu and its transletions.
2. Then i added LocalizationPart to Taxonomy Link and i have created "relation" between menu from step 1 and Taxonomy. But when i tried create a translation of this Taxonomy Link, i noticed that it isn't shown anywhere. It didn't go to Menu with the same language...
3. I created a Menu Widget (i added LocalizationPart to this content type). But if i tried to translate it, it went down to error in Modules\Orchard.Widgets\Views\EditorTemplates\Parts.Widgets.WidgetPart.cshtml    Line: 10...

Are my steps OK? I don't want always disturb you, where can i ask? Or where can i place this issue?

**Comment by urbanit** [comment]
@loshuliveros i think that creating a localized menu is kinda of trouble. Instead you may create 2 menus and place them to different layers based on culture.

**Comment by Piedone** [comment]
@urbanit is right, localized menus are a multi-fold trouble and not solved by this module. For general Orchard discussions please visit: https://orchard.codeplex.com/discussions

**Comment by loshuliveros** [comment]
Thanks, for an advice :-) It's strange for me, because i thought that Orchard is something like little brother of Drupal, there are a lots of smilar functionalities (Block in Drupal is Widget in Orchard, Regions are Zones, Views are Projections etc.)... But Drupal's i18n module works perfect, why not inspire there?

OK, i have to use urbanit's solution even if it's not clean as i expected...

BTW, problem with widget translation is general, i've tried it later on Text Widget too and i wasn't able to add translation... It's strange too, because it worked before in Orchard 1.8...

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/Orchard/issues/5031
